INSERT INTO softwareTest.hardware (raeume_r_id, lieferant_l_id, h_name, h_bez, h_einkaufsdatum, h_gewaehrleistungsdauer, h_notiz, h_hersteller, hardwarearten_ha_id) VALUES (2, 2, 'PC_002', 'ThinkCenter M92P', '2017-07-25', 1000, '', 'Lenovo', 1);
INSERT INTO softwareTest.hardware (raeume_r_id, lieferant_l_id, h_name, h_bez, h_einkaufsdatum, h_gewaehrleistungsdauer, h_notiz, h_hersteller, hardwarearten_ha_id) VALUES (10, 1, 'PC_002', 'Generic PC 1', '2017-07-25', 1000, null, 'DELL', 1);
INSERT INTO softwareTest.hardware (raeume_r_id, lieferant_l_id, h_name, h_bez, h_einkaufsdatum, h_gewaehrleistungsdauer, h_notiz, h_hersteller, hardwarearten_ha_id) VALUES (7, 1, 'PC_003o', 'Generic PC 2', '2017-07-25', 1000, '', 'DELL', 1);
INSERT INTO softwareTest.hardware (raeume_r_id, lieferant_l_id, h_name, h_bez, h_einkaufsdatum, h_gewaehrleistungsdauer, h_notiz, h_hersteller, hardwarearten_ha_id) VALUES (2, 1, 'Switch_001', 'Generic Switch', '2017-07-25', 1000, null, 'Switcherino', 2);
INSERT INTO softwareTest.hardware (raeume_r_id, lieferant_l_id, h_name, h_bez, h_einkaufsdatum, h_gewaehrleistungsdauer, h_notiz, h_hersteller, hardwarearten_ha_id) VALUES (2, 5, 'Drucker_005', 'Generic Drucker', '2017-07-25', 1000, null, 'Druckerino', 5);
INSERT INTO softwareTest.hardware (raeume_r_id, lieferant_l_id, h_name, h_bez, h_einkaufsdatum, h_gewaehrleistungsdauer, h_notiz, h_hersteller, hardwarearten_ha_id) VALUES (2, 1, 'PC_004', 'Generic PC 4', '2017-07-25', 1000, '', 'DELLERINO', 1);
INSERT INTO softwareTest.hardware (raeume_r_id, lieferant_l_id, h_name, h_bez, h_einkaufsdatum, h_gewaehrleistungsdauer, h_notiz, h_hersteller, hardwarearten_ha_id) VALUES (2, 7, 'Special PC 2', 'GLaDiOS', '2017-07-25', 1000, null, 'DELL', 1);
INSERT INTO softwareTest.hardware (raeume_r_id, lieferant_l_id, h_name, h_bez, h_einkaufsdatum, h_gewaehrleistungsdauer, h_notiz, h_hersteller, hardwarearten_ha_id) VALUES (1, 2, 'PC_006', 'Generic PC ji', '2017-07-25', 1000, '', 'DELLERINO', 1);
INSERT INTO softwareTest.hardware (raeume_r_id, lieferant_l_id, h_name, h_bez, h_einkaufsdatum, h_gewaehrleistungsdauer, h_notiz, h_hersteller, hardwarearten_ha_id) VALUES (4, 1, 'PC_008', 'Generic PC 8', '2017-07-25', 1000, null, 'DELLERINO', 1);
INSERT INTO softwareTest.hardware (raeume_r_id, lieferant_l_id, h_name, h_bez, h_einkaufsdatum, h_gewaehrleistungsdauer, h_notiz, h_hersteller, hardwarearten_ha_id) VALUES (1, 1, 'PC_009', 'Generic PC 9', '2017-07-29', 1000, '', 'DELLicious', 1);
INSERT INTO softwareTest.hardware (raeume_r_id, lieferant_l_id, h_name, h_bez, h_einkaufsdatum, h_gewaehrleistungsdauer, h_notiz, h_hersteller, hardwarearten_ha_id) VALUES (6, 1, 'Special PC 4', 'Hoellenmaschine', '2017-07-25', 1000, null, 'DELLERINO', 1);
INSERT INTO softwareTest.hardware (raeume_r_id, lieferant_l_id, h_name, h_bez, h_einkaufsdatum, h_gewaehrleistungsdauer, h_notiz, h_hersteller, hardwarearten_ha_id) VALUES (1, 6, 'PC_011', 'Generic PC 11', '2017-07-25', 1000, null, 'DELL', 1);
INSERT INTO softwareTest.hardware (raeume_r_id, lieferant_l_id, h_name, h_bez, h_einkaufsdatum, h_gewaehrleistungsdauer, h_notiz, h_hersteller, hardwarearten_ha_id) VALUES (3, 1, 'PC_012', 'Generic PC 12', '2017-07-25', 1000, null, 'DELLERINO', 1);
INSERT INTO softwareTest.hardware (raeume_r_id, lieferant_l_id, h_name, h_bez, h_einkaufsdatum, h_gewaehrleistungsdauer, h_notiz, h_hersteller, hardwarearten_ha_id) VALUES (4, 1, 'PC_013', 'Generic PC 13', '2017-07-25', 1000, null, 'Lenovo', 1);
INSERT INTO softwareTest.hardware (raeume_r_id, lieferant_l_id, h_name, h_bez, h_einkaufsdatum, h_gewaehrleistungsdauer, h_notiz, h_hersteller, hardwarearten_ha_id) VALUES (5, 7, 'PC_014', 'Generic PC 14', '2017-07-25', 1000, null, 'DELLERINO', 1);
INSERT INTO softwareTest.hardware (raeume_r_id, lieferant_l_id, h_name, h_bez, h_einkaufsdatum, h_gewaehrleistungsdauer, h_notiz, h_hersteller, hardwarearten_ha_id) VALUES (6, 1, 'PC_015', 'Kartoffel PC', '2017-07-25', 1000, null, 'DELL', 1);
INSERT INTO softwareTest.hardware (raeume_r_id, lieferant_l_id, h_name, h_bez, h_einkaufsdatum, h_gewaehrleistungsdauer, h_notiz, h_hersteller, hardwarearten_ha_id) VALUES (7, 5, 'PC_016', 'Generic PC 16', '2017-07-25', 1000, null, 'Lenovo', 1);
INSERT INTO softwareTest.hardware (raeume_r_id, lieferant_l_id, h_name, h_bez, h_einkaufsdatum, h_gewaehrleistungsdauer, h_notiz, h_hersteller, hardwarearten_ha_id) VALUES (7, 1, 'PC_017', 'Generic PC 17', '2017-07-25', 1000, null, 'DELL', 1);

INSERT INTO softwareTest.hardware_hat_attribute (hardware_h_id, hardwareattribute_hat_id, hhhat_wert) VALUES (1, 1, 'i7-7700K');
INSERT INTO softwareTest.hardware_hat_attribute (hardware_h_id, hardwareattribute_hat_id, hhhat_wert) VALUES (1, 2, '8GB');
INSERT INTO softwareTest.hardware_hat_attribute (hardware_h_id, hardwareattribute_hat_id, hhhat_wert) VALUES (1, 3, '285285825');
INSERT INTO softwareTest.hardware_hat_attribute (hardware_h_id, hardwareattribute_hat_id, hhhat_wert) VALUES (1, 4, '512GB');
INSERT INTO softwareTest.hardware_hat_attribute (hardware_h_id, hardwareattribute_hat_id, hhhat_wert) VALUES (1, 5, 'SSD');
INSERT INTO softwareTest.hardware_hat_attribute (hardware_h_id, hardwareattribute_hat_id, hhhat_wert) VALUES (1, 6, '1x HDMI, 2x VGA');

INSERT INTO softwareTest.hardwarearten (ha_hardwareart) VALUES ('PC');
INSERT INTO softwareTest.hardwarearten (ha_hardwareart) VALUES ('Switch');
INSERT INTO softwareTest.hardwarearten (ha_hardwareart) VALUES ('Router');
INSERT INTO softwareTest.hardwarearten (ha_hardwareart) VALUES ('Accesspoint');
INSERT INTO softwareTest.hardwarearten (ha_hardwareart) VALUES ('Drucker');
INSERT INTO softwareTest.hardwarearten (ha_hardwareart) VALUES ('Beamer');
INSERT INTO softwareTest.hardwarearten (ha_hardwareart) VALUES ('Visualizer');
INSERT INTO softwareTest.hardwarearten (ha_hardwareart) VALUES ('Software');

INSERT INTO softwareTest.hardwareattribute (hat_bezeichnung) VALUES ('CPU');
INSERT INTO softwareTest.hardwareattribute (hat_bezeichnung) VALUES ('RAM');
INSERT INTO softwareTest.hardwareattribute (hat_bezeichnung) VALUES ('Seriennummer');
INSERT INTO softwareTest.hardwareattribute (hat_bezeichnung) VALUES ('Festplatte');
INSERT INTO softwareTest.hardwareattribute (hat_bezeichnung) VALUES ('Festplattentyp');
INSERT INTO softwareTest.hardwareattribute (hat_bezeichnung) VALUES ('Grafikausgang');
INSERT INTO softwareTest.hardwareattribute (hat_bezeichnung) VALUES ('Portanzahl');
INSERT INTO softwareTest.hardwareattribute (hat_bezeichnung) VALUES ('Uplinktyp');
INSERT INTO softwareTest.hardwareattribute (hat_bezeichnung) VALUES ('IP1');
INSERT INTO softwareTest.hardwareattribute (hat_bezeichnung) VALUES ('IP2');
INSERT INTO softwareTest.hardwareattribute (hat_bezeichnung) VALUES ('IP3');
INSERT INTO softwareTest.hardwareattribute (hat_bezeichnung) VALUES ('IP4');
INSERT INTO softwareTest.hardwareattribute (hat_bezeichnung) VALUES ('WLAN-Standard');
INSERT INTO softwareTest.hardwareattribute (hat_bezeichnung) VALUES ('Druckertyp');
INSERT INTO softwareTest.hardwareattribute (hat_bezeichnung) VALUES ('DruckerArt');
INSERT INTO softwareTest.hardwareattribute (hat_bezeichnung) VALUES ('Druckformat');
INSERT INTO softwareTest.hardwareattribute (hat_bezeichnung) VALUES ('Beidseitig');
INSERT INTO softwareTest.hardwareattribute (hat_bezeichnung) VALUES ('ANSI-Lumen');
INSERT INTO softwareTest.hardwareattribute (hat_bezeichnung) VALUES ('Eingang');
INSERT INTO softwareTest.hardwareattribute (hat_bezeichnung) VALUES ('Lautsprecher');

INSERT INTO softwareTest.lieferant (l_firmenname, l_strasse, l_plz, l_ort, l_tel, l_mobil, l_fax, l_email, l_ausgemustert) VALUES ('MindFactorO', 'Derpstreet 8', '91714', 'Derptown', '091482585', '01858152', '01851525', 'derp@derptown.de', 0);
INSERT INTO softwareTest.lieferant (l_firmenname, l_strasse, l_plz, l_ort, l_tel, l_mobil, l_fax, l_email, l_ausgemustert) VALUES ('MindFactory', 'street 8', '91714', 'Derptown', '091482585', '01858152', '01851525', 'derp@derptown.de', 0);
INSERT INTO softwareTest.lieferant (l_firmenname, l_strasse, l_plz, l_ort, l_tel, l_mobil, l_fax, l_email, l_ausgemustert) VALUES ('Trump Deliveries', 'TRUMP Lane 666', '69696', 'TRUMP City', '12345667', '0632489', '0525266', 'dinoracing@yahoo.com', 0);
INSERT INTO softwareTest.lieferant (l_firmenname, l_strasse, l_plz, l_ort, l_tel, l_mobil, l_fax, l_email, l_ausgemustert) VALUES ('Trompeten Bauer', 'Didgerido 465', '09123', 'Tartarus', '999999', '666666', '123213', 'hiddenRealm@trick.info', 0);
INSERT INTO softwareTest.lieferant (l_firmenname, l_strasse, l_plz, l_ort, l_tel, l_mobil, l_fax, l_email, l_ausgemustert) VALUES ('Creeper Inc.', 'Error 404', '01010', 'minecraft', '867346', '23154', '67535', 'dev@mojang.com', 0);
INSERT INTO softwareTest.lieferant (l_firmenname, l_strasse, l_plz, l_ort, l_tel, l_mobil, l_fax, l_email, l_ausgemustert) VALUES ('Brennholzverleih', 'Brennweg 21', '21212', 'MittenImWald', '41236354', '1234665', '4242134', 'flachwitz@spaß.org', 0);

INSERT INTO softwareTest.raeume (r_nr, r_bezeichnung, r_notiz, r_ausgemustert) VALUES ('999', 'Ausmusterraums', 'Nur Ausmusterung', 0);
INSERT INTO softwareTest.raeume (r_nr, r_bezeichnung, r_notiz, r_ausgemustert) VALUES ('001', 'Klassenzimmer 1', ' <b>huehue</b>', 0);
INSERT INTO softwareTest.raeume (r_nr, r_bezeichnung, r_notiz, r_ausgemustert) VALUES ('314', 'Serverraum', ' ', 0);
INSERT INTO softwareTest.raeume (r_nr, r_bezeichnung, r_notiz, r_ausgemustert) VALUES ('002', 'Vorbereitungsraum', 'Raum zum vorbereiten', 0);
INSERT INTO softwareTest.raeume (r_nr, r_bezeichnung, r_notiz, r_ausgemustert) VALUES ('003', 'Klassenzimmer 2', ' ', 0);
INSERT INTO softwareTest.raeume (r_nr, r_bezeichnung, r_notiz, r_ausgemustert) VALUES ('004', 'Folterkammer 29', '......', 0);
INSERT INTO softwareTest.raeume (r_nr, r_bezeichnung, r_notiz, r_ausgemustert) VALUES ('005', 'Klassenzimmer', ' ', 0);
INSERT INTO softwareTest.raeume (r_nr, r_bezeichnung, r_notiz, r_ausgemustert) VALUES ('006', 'RAUM 404', 'nicht auffindbar', 0);
INSERT INTO softwareTest.raeume (r_nr, r_bezeichnung, r_notiz, r_ausgemustert) VALUES ('007', 'Huepfburgraum', 'much trampoline, very fun', 0);
INSERT INTO softwareTest.raeume (r_nr, r_bezeichnung, r_notiz, r_ausgemustert) VALUES ('008', 'Klassenzimmer 3', ' ', 0);
INSERT INTO softwareTest.raeume (r_nr, r_bezeichnung, r_notiz, r_ausgemustert) VALUES ('009', 'Puppenraum', 'nicht in die Augen sehen', 0);

INSERT INTO softwareTest.wird_beschrieben_durch (hardwarearten_ha_id, hardwareattribute_hat_id) VALUES (1, 1);
INSERT INTO softwareTest.wird_beschrieben_durch (hardwarearten_ha_id, hardwareattribute_hat_id) VALUES (1, 2);
INSERT INTO softwareTest.wird_beschrieben_durch (hardwarearten_ha_id, hardwareattribute_hat_id) VALUES (1, 3);
INSERT INTO softwareTest.wird_beschrieben_durch (hardwarearten_ha_id, hardwareattribute_hat_id) VALUES (1, 4);
INSERT INTO softwareTest.wird_beschrieben_durch (hardwarearten_ha_id, hardwareattribute_hat_id) VALUES (1, 5);
INSERT INTO softwareTest.wird_beschrieben_durch (hardwarearten_ha_id, hardwareattribute_hat_id) VALUES (1, 6);
INSERT INTO softwareTest.wird_beschrieben_durch (hardwarearten_ha_id, hardwareattribute_hat_id) VALUES (2, 3);
INSERT INTO softwareTest.wird_beschrieben_durch (hardwarearten_ha_id, hardwareattribute_hat_id) VALUES (2, 7);
INSERT INTO softwareTest.wird_beschrieben_durch (hardwarearten_ha_id, hardwareattribute_hat_id) VALUES (2, 8);
INSERT INTO softwareTest.wird_beschrieben_durch (hardwarearten_ha_id, hardwareattribute_hat_id) VALUES (3, 3);
INSERT INTO softwareTest.wird_beschrieben_durch (hardwarearten_ha_id, hardwareattribute_hat_id) VALUES (3, 7);
INSERT INTO softwareTest.wird_beschrieben_durch (hardwarearten_ha_id, hardwareattribute_hat_id) VALUES (3, 9);
INSERT INTO softwareTest.wird_beschrieben_durch (hardwarearten_ha_id, hardwareattribute_hat_id) VALUES (3, 10);
INSERT INTO softwareTest.wird_beschrieben_durch (hardwarearten_ha_id, hardwareattribute_hat_id) VALUES (3, 11);
INSERT INTO softwareTest.wird_beschrieben_durch (hardwarearten_ha_id, hardwareattribute_hat_id) VALUES (3, 12);
INSERT INTO softwareTest.wird_beschrieben_durch (hardwarearten_ha_id, hardwareattribute_hat_id) VALUES (4, 3);
INSERT INTO softwareTest.wird_beschrieben_durch (hardwarearten_ha_id, hardwareattribute_hat_id) VALUES (4, 13);
INSERT INTO softwareTest.wird_beschrieben_durch (hardwarearten_ha_id, hardwareattribute_hat_id) VALUES (5, 3);
INSERT INTO softwareTest.wird_beschrieben_durch (hardwarearten_ha_id, hardwareattribute_hat_id) VALUES (5, 14);
INSERT INTO softwareTest.wird_beschrieben_durch (hardwarearten_ha_id, hardwareattribute_hat_id) VALUES (5, 15);
INSERT INTO softwareTest.wird_beschrieben_durch (hardwarearten_ha_id, hardwareattribute_hat_id) VALUES (5, 16);
INSERT INTO softwareTest.wird_beschrieben_durch (hardwarearten_ha_id, hardwareattribute_hat_id) VALUES (5, 17);
INSERT INTO softwareTest.wird_beschrieben_durch (hardwarearten_ha_id, hardwareattribute_hat_id) VALUES (6, 3);
INSERT INTO softwareTest.wird_beschrieben_durch (hardwarearten_ha_id, hardwareattribute_hat_id) VALUES (6, 18);
INSERT INTO softwareTest.wird_beschrieben_durch (hardwarearten_ha_id, hardwareattribute_hat_id) VALUES (6, 19);
INSERT INTO softwareTest.wird_beschrieben_durch (hardwarearten_ha_id, hardwareattribute_hat_id) VALUES (6, 20);
INSERT INTO softwareTest.wird_beschrieben_durch (hardwarearten_ha_id, hardwareattribute_hat_id) VALUES (7, 3);

INSERT INTO softwareTest.software (s_name, s_bez, s_einkaufsdatum, s_lizenzlaufzeit, s_notiz, s_hersteller, s_vnr, s_lizenztyp, s_anzahl, s_lizenzinformation, s_installhinweis) VALUES ('WinRar', 'WinRarR', '2007-12-20', 23535334, 'Ist gekauft', 'NoOnePay', '234234234', 23, 230023, 'Super', 'Nicht mit anderer gleichzeitig laufen lassen');
INSERT INTO softwareTest.software (s_name, s_bez, s_einkaufsdatum, s_lizenzlaufzeit, s_notiz, s_hersteller, s_vnr, s_lizenztyp, s_anzahl, s_lizenzinformation, s_installhinweis) VALUES ('', 'awfawfawf', null, 0, '', '', '', 0, 0, '', '');
INSERT INTO softwareTest.software (s_name, s_bez, s_einkaufsdatum, s_lizenzlaufzeit, s_notiz, s_hersteller, s_vnr, s_lizenztyp, s_anzahl, s_lizenzinformation, s_installhinweis) VALUES ('awfawfawf', '', null, 0, '', '', '', 0, 0, '', '');
INSERT INTO softwareTest.software (s_name, s_bez, s_einkaufsdatum, s_lizenzlaufzeit, s_notiz, s_hersteller, s_vnr, s_lizenztyp, s_anzahl, s_lizenzinformation, s_installhinweis) VALUES ('qq', '', null, 0, '', '', '', 0, 0, '', '');

INSERT INTO softwareTest.software_in_raum (sir_h_id, sir_r_id) VALUES (1, 3);